// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG6aJGm9zVq2PTCORB009k7l-DOKorjio',
    appId: '1:296954241208:web:efda58c0917f1fcb9cd44d',
    messagingSenderId: '296954241208',
    projectId: 'loginpage-a8e56',
    authDomain: 'loginpage-a8e56.firebaseapp.com',
    storageBucket: 'loginpage-a8e56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_pUg4M87UDnrQj17x0I7J4CZSJFRmtY',
    appId: '1:296954241208:android:1b3fe2c41253aa419cd44d',
    messagingSenderId: '296954241208',
    projectId: 'loginpage-a8e56',
    storageBucket: 'loginpage-a8e56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqmpx31s3w-TfLg35QDtb-6iJVmK2LRXE',
    appId: '1:296954241208:ios:ffad421e318a31f39cd44d',
    messagingSenderId: '296954241208',
    projectId: 'loginpage-a8e56',
    storageBucket: 'loginpage-a8e56.appspot.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqmpx31s3w-TfLg35QDtb-6iJVmK2LRXE',
    appId: '1:296954241208:ios:0cecb2016fe17f0e9cd44d',
    messagingSenderId: '296954241208',
    projectId: 'loginpage-a8e56',
    storageBucket: 'loginpage-a8e56.appspot.com',
    iosBundleId: 'com.example.loginpage.RunnerTests',
  );
}
